---
# defaults file for boot-for-rhcos
RHCOS_KERNEL_PATH: http://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.7/4.7.0
RHCOS_BOOT_DISK: hd0,msdos1
#RHCOS_BOOT_DISK: hd0,gpt1
RHCOS_BOOT_PATH: ''
RHCOS_BOOT_KERNEL: rhcos-live-kernel-x86_64
RHCOS_BOOT_INITRD: rhcos-live-initramfs.x86_64.img
RHCOS_BOOT_ROOTFS: rhcos-live-rootfs.x86_64.img
RHCOS_NET_DEV: ''
RHCOS_IP: ip={{ ansible_default_ipv4['address'] }}:{{ RHCOS_NET_DEV }}:{{ ansible_default_ipv4['gateway'] }}:{{ ansible_default_ipv4['netmask'] }}:{{ inventory_hostname }}::none 
RHCOS_INSTALL_DEV: sda
RHCOS_OPTS: ''
RHCOS_IGN_PATH: 'http://bastion.example.com/ocp4/ign'
